---

- name: Install various packages
  apt: name="{{ item }}" update_cache=yes
  with_items:
    # Install Python 3
#    - python3-dev
#    - python3-venv
#    - python3-pip

    # Install other essential packages
    - build-essential
    - curl
    - libssl-dev
    - libbz2-dev
    - libffi-dev
    - libreadline-dev
    - libsqlite3-dev
    - libncurses5-dev
    - libncursesw5-dev
    - llvm
    - sendmail
    - tk-dev
    - xz-utils
    - wget