---

- name: Install postgres required packages
  apt: name={{ item }} update_cache=yes
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
    - postgresql-client-common
    - postgresql-client
    - postgresql-contrib
    # - libjpeg-dev
    # - libjpeg62
    # - libjpeg62-dev
    # - zlib1g-dev
    # - libfreetype6-dev
  become: yes

- name: Ensure database is created
  postgresql_db: 
    name: "{{ DB_NAME }}"
  become_user: postgres
  become: yes

- name: Create new PostgreSQL user
  postgresql_user:
    db: "{{ DB_NAME }}"
    name: "{{ DB_USER }}"
    password: "{{ db_pwd }}"
    encrypted: yes
    priv: ALL
    role_attr_flags: NOSUPERUSER
  become_user: postgres
  become: yes

- name: Change database owner
  postgresql_db:
    name: "{{ DB_NAME }}"
    owner: "{{ DB_USER }}"
  become_user: postgres
  become: yes

#- name: Install Redis required packages
#  apt: name=redis-server update_cache=yes
#  become: yes
