---

- name: Install supervisor (globally)
  pip: name="supervisor"
  become: yes

- name: Configure supervisor
  template:
    src: "supervisord.conf.j2"
    dest: "{{ SUPERVISOR_DIR_PATH }}/supervisord.conf"
    owner: "{{ DEPLOY_USER }}"
    group: "{{ DEPLOY_GROUP }}"
    mode: "0644"

- name: Ensure supervisor is not running (we're not done yet)
  supervisorctl:
    name:
    state: started