---

- name: Server configuration at birth
  hosts: all
  gather_facts: no
  remote_user: "{{ ROOT }}"
  pre_tasks:
    - name: Apt update && upgrade && install Python 2
      raw: apt-get -y update && apt-get -y upgrade && apt-get -y install python-dev python-pip
    - name: Upgrade pip to latest version
      pip: name=pip state=latest
  vars_prompt:
    - name: "prompt_user_password"
      prompt: "Enter password for new user"
      encrypt: "sha512_crypt"
      private: yes
      confirm: yes
  roles:
    - birth
